import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
const inter = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "UM e-Wisdom",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html className="h-full w-full" lang="en">
      <body className={`${inter.className} h-full w-full`}>
        {children}
        <Toaster />
      </body>
    </html>
  );
}
